### ISSUE TITLE
PyCrypto Vulnerability

### ISSUE THREAD

**Issue by josephklein** [discogs/python-cas-client#9]
PyCrypto is [no longer maintained and has some vulnerabilities](https://github.com/dlitz/pycrypto/issues/285). Updating to [pycryptodome](https://github.com/Legrandin/pycryptodome) seems to be the recommended fix. It should just be a matter of updating the dependency in `requirements.txt`, and shouldn't require any code change.

**Comment by brephophagist** [comment]
Thanks for the report! We'll have an updated version in PyPi soon. (See #10)

**Comment by brephophagist** [comment]
[v0.1.6](https://github.com/discogs/python-cas-client/releases/tag/v0.1.6) has been released containing this proposed change. Thanks again for your report!
